name: Deploy to Firebase Hosting
# ワークフローが実行されるタイミングを定義
on:
  push:
    branches:
      - main  # mainブランチにプッシュされた時に実行

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # ワークフローを実行する仮想環境
    steps:
      # 1. リポジトリのソースコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node.jsの環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # プロジェクトで使用しているNode.jsのバージョンを指定

# 3. Reactアプリの依存関係をインストールし、ビルド
      - name: Install and Build
        run: |
          cd frontend
          npm ci
          npm run build
        env: # このenvブロックを丸ごと追加してください
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}